spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=postgres
spring.datasource.password=ROOT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

jwt.secret=8f2b91d4e6a730c1f5b8d29e47a6c3f0912e8b7d4a5c6f3e2d1b0a9c8e7f6d5c
jwt.expiration=86400000